### ISSUE TITLE
Manual Installation of CML on instance using the  ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230918

### ISSUE THREAD

**Issue by osacalsaw** [CiscoDevNet/cloud-cml#22]
We are able to deploy a bare metal instance on the console using the  ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230918  as per the CML terraform code. But we are not able to deploy using Terraform as per the guidelines (The Terraform user is prevented for creating resources due to a Service Control Policy that due to organizational policies, cannot be removed). With the bare metal instance deployed on the console, is there a way to manually deploy and install the CML software and refplat files on the instance? Are there any directions for this? We have the refplat files and CML software in an S3 bucket.

**Comment by rschmied** [comment]
very roughly, and from the top of my head (as this is venturing into uncharted/unsupported land):

- copy the `cml2*.pkg` file to the server
- extract the `.deb` packages from the `cml2*.pkg` using `tar`
- install the `cml*.deb`, `patty*.deb` and `iol-tools*.deb` packages on the server
- look at the `cml.sh` file from this repository to get some ideas how the configuration works
    - `modules/deploy/data/cml.sh`
    - `modules/deploy/data/virl2-base-config.yml`
 - the initial configuration services consumes the data from the `virl2-base-config.yml` file
 - you need to copy all the node and image definitions and actual images from S3 to the VM (suggest to use `aws s3 sync`), they go into `/var/lib/libvirt/images/virl2-base-images` and `/var/lib/libvirt/images/node-definitions`.
 - licensing of the system is best done then via the actual UI

it's also up to you at this point how to provide IP access to the system...

**Comment by rschmied** [comment]
@osacalsaw : Were you able to resolve this?  I am closing this for now but feel free to re-open it, if needed.
