### ISSUE TITLE
Azure deployment issues

### ISSUE THREAD

**Issue by kellermatthis** [CiscoDevNet/cloud-cml#23]
**Describe the bug**
When publishing to Azure, a Terraform error message is displayed, which refers to the allocation method of the public IP.  A warning is also issued which refers to an deprecated attribute. And last but not least, the Azure tutorial is confusing as it shows an partly outdated screenshot and does not mention the necessary change of a mandatory variable.

**To Reproduce**
1. Select Azure deployment and prepare repo accordingly
2. Replace Terraform variables with your own values
3. execute "terraform plan"
4. See warning
5. execute "terraform apply"
6. See error

**Expected behavior**
It is expected that terraform plan and apply will be executed without warnings or errors.

**Screenshots**
Warning (after terraform plan):
<img width="514" alt="image" src="https://github.com/user-attachments/assets/3a230b2e-0b2e-4e69-ac39-c59f3f3b2b39">

IP error (after terraform apply):
<img width="638" alt="image" src="https://github.com/user-attachments/assets/57e60ae3-c05e-4274-b7d3-18a6c32c7ea9">

**Software versions (please complete the following information):**
 - OS: Windows 11
 - Terraform version: 1.9.8
 - Plugin version: Azure cli 2.65.0, cml2 2.7.2

**Additional context**
Related PR: #24

**Comment by rschmied** [comment]
thanks @kellermatthis for bringing this up.  In fact, I saw this myself last week when running some demo VM in Azure.  I haven't had time to address this on GH so your contribution is most welcome.

The `use_cache` thing is purely cosmetic -- I dreprectated that option in the last Terraform release.  But besides showing that warning, there's nothing to worry about.

**Comment by kellermatthis** [comment]
Thanks for approving the pull request
