### ISSUE TITLE
It's not very clear where to get Debian package with the CML2 software

### ISSUE THREAD

**Issue by audacious-lab** [CiscoDevNet/cloud-cml#3]
My download section only have these 4 files available:

- refplat_p-20230117-fcs.iso.zip
- cml2_p_2.6.0-5_amd64-6.iso.zip
- cml2_p_2.6.0-5_amd64-6.ova
- cml2_p_2.6.0-5_amd64-6.pkg.zip

Example from config.yaml

deb: cml2_2.5.1-10_amd64.deb

**Comment by rschmied** [comment]
thanks for raising this issue, @audacious-lab . The Debian package is included in the .pkg.zip file which, when you unzip it, is basically a tar file.

you can put the .pkg file (not the .zip) into the directory where the upload tool runs and it will pick it up. however, I need to update the documentation to make this clearer.

**Comment by audacious-lab** [comment]
Thanks, I was able to unpack this .deb file from .pkg

**Comment by rschmied** [comment]
I'll leave this open until I have pushed the documentation update.
