### ISSUE TITLE
No EBS encryption support

### ISSUE THREAD

**Issue by orndor** [CiscoDevNet/cloud-cml#8]
If your default EC2 security settings are set to encrypt all new EBS volumes, the Terraform job will fail with the following error:

```
│ Error: waiting for EC2 Instance (i-XXXXXXXXXXXXX) create: unexpected state 'shutting-down', wanted target 'running'. 
│ last error: Client.InvalidKMSKey.InvalidState: The KMS key provided is in an incorrect state
│ 
│   with module.deploy.aws_instance.cml,
│   on module-cml2-deploy-aws/main.tf line 125, in resource "aws_instance" "cml":
│  125: resource "aws_instance" "cml" {
```

Likely, additional instructions are required in the README to modify IAM permissions to allow the appropriate access to KMS.  However, a work around is to temporarily disable the default encryption state of all new EBS volumes:
AWS Console -> EC2 Dashboard -> Data Protection and security (upper right-hand corner) -> EBS Encryption -> Manage -> Uncheck 'Enable'

**Comment by rschmied** [comment]
Hi, @orndor .. Thanks.  Obviously, I didn't run into this myself so far.  What would be the preferred solution here?  Changing the policy or applying the workaround?

**Comment by orndor** [comment]
Hi @rschmied!  Changing the required policy for KMS would be preferred.  I gather Enterprise users might have AWS governance polices which require EBS encryption by default.
